/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WallOfPapersRouteImport } from './routes/wall-of-papers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkAtChar123companyChar125RouteImport } from './routes/work.@{$company}'

const WallOfPapersRoute = WallOfPapersRouteImport.update({
  id: '/wall-of-papers',
  path: '/wall-of-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkAtChar123companyChar125Route =
  WorkAtChar123companyChar125RouteImport.update({
    id: '/work/@{$company}',
    path: '/work/@{$company}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wall-of-papers': typeof WallOfPapersRoute
  '/work/@{$company}': typeof WorkAtChar123companyChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wall-of-papers': typeof WallOfPapersRoute
  '/work/@{$company}': typeof WorkAtChar123companyChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wall-of-papers': typeof WallOfPapersRoute
  '/work/@{$company}': typeof WorkAtChar123companyChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wall-of-papers' | '/work/@{$company}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wall-of-papers' | '/work/@{$company}'
  id: '__root__' | '/' | '/wall-of-papers' | '/work/@{$company}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WallOfPapersRoute: typeof WallOfPapersRoute
  WorkAtChar123companyChar125Route: typeof WorkAtChar123companyChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wall-of-papers': {
      id: '/wall-of-papers'
      path: '/wall-of-papers'
      fullPath: '/wall-of-papers'
      preLoaderRoute: typeof WallOfPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/@{$company}': {
      id: '/work/@{$company}'
      path: '/work/@{$company}'
      fullPath: '/work/@{$company}'
      preLoaderRoute: typeof WorkAtChar123companyChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WallOfPapersRoute: WallOfPapersRoute,
  WorkAtChar123companyChar125Route: WorkAtChar123companyChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
